name: lmql
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pytorch::pytorch=1.11.0
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=11.7
  - conda-forge::nodejs=18.15
  - pip:
    - astunparse
    - openai
    - termcolor
    - pydot
    - transformers==4.25.1
    - pandas
    - accelerate
